# Generated by Django 2.2.6 on 2019-10-29 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StitchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Stitch_type',
                'verbose_name_plural': 'stitch_types',
                'db_table': 'stitch_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StitchTypeDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('stitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stitchTypes.StitchType')),
            ],
            options={
                'verbose_name': 'stitch_type_design',
                'verbose_name_plural': 'stitch_type_designs',
                'db_table': 'stitch_type_design',
                'managed': True,
            },
        ),
    ]
