# Generated by Django 2.2.6 on 2019-11-22 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products_api.stitch.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
            ],
            options={
                'db_table': 'knit_vendor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=products_api.stitch.models.uploadFolder)),
                ('source', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'knit_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stype', models.CharField(default=None, max_length=80, null=True)),
                ('code', models.CharField(default=None, max_length=80, null=True)),
                ('description', models.CharField(default=None, max_length=80, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Knit Stitch Ref Table',
                'verbose_name_plural': 'Knit Stitch Ref Table',
                'db_table': 'knit_stitch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StitchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stype', models.CharField(default=None, max_length=80, null=True)),
                ('code', models.CharField(default=None, max_length=80, null=True)),
                ('description', models.CharField(default=None, max_length=120, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('stitch', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='stitch.Stitch')),
            ],
            options={
                'verbose_name': 'Knit Stitch Type Ref Table',
                'verbose_name_plural': 'Knit Stitch Type Ref Table',
                'db_table': 'knit_stitch_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StitchTypeDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdesign', models.CharField(default=None, max_length=80, null=True)),
                ('code', models.CharField(default=None, max_length=80, null=True)),
                ('description', models.CharField(default=None, max_length=120, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('stitch_type', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='stitch.StitchType')),
            ],
            options={
                'verbose_name': 'Knit Stitch Type design',
                'verbose_name_plural': 'Knit Stitch Type design',
                'db_table': 'knit_stitch_type_design',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=80, null=True)),
                ('title', models.CharField(default=None, max_length=80, null=True)),
                ('description', models.CharField(default=None, max_length=120, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('stitch', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stitch.Stitch')),
                ('stitch_type', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stitch.StitchType')),
                ('stitch_type_design', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stitch.StitchTypeDesign')),
                ('vendor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stitch.Vendor')),
            ],
            options={
                'verbose_name': 'Knit Product',
                'verbose_name_plural': 'Knit Products',
                'db_table': 'knit_product',
                'managed': True,
            },
        ),
    ]
