# Generated by Django 2.2.6 on 2019-11-22 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stitch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='stitch.Vendor'),
        ),
    ]
