# Generated by Django 2.2.6 on 2019-11-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stitch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor',
            new_name='user',
        ),
    ]
