# Generated by Django 2.2.6 on 2019-11-24 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stitch', '0003_auto_20191123_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stitch.KImage'),
        ),
        migrations.AddField(
            model_name='stitch',
            name='images',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stitch.KImage'),
        ),
        migrations.AddField(
            model_name='stitchtype',
            name='images',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stitch.KImage'),
        ),
        migrations.AddField(
            model_name='stitchtypedesign',
            name='images',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stitch.KImage'),
        ),
    ]
